add component and rework for Dapr 1.10
danbugs/spin-dapr-poc pull request #1
Opened 2023-04-18 18:36 UTC by KaiWalter

After @radu-matei pointed me to this sample at KubeCon today I had to give it a _spin_ - hope you don't mind my minor corrections.

2023-04-22 20:06 UTC, danbugs commented
Thank you so much for your PR!

I've tried running your update locally w/ the updated Dapr CLI, and runtime, but I'm no longer getting the orderId output in the body of the GET request. The body being empty would suggest the POST is failing. Am I missing something?

2023-04-23 06:22 UTC, KaiWalter commented
OK, then I experienced that same missing response (the other way around) with my local configuration, that is why I adapted. Let me look into this more thoroughly.

2023-04-23 07:46 UTC, KaiWalter commented
OK, to dissect a bit. When running from **main** branch with this Dapr configuration

```
$ dapr --version
CLI version: 1.10.0
Runtime version: 1.10.5
```

I get this error

```
ERRO[0000] error getting topics from app: json: cannot unmarshal object into Go value of type []pubsub.SubscriptionJSON  app_id=spin-dapr-poc instance=kw-devvm scope=dapr.runtime type=log ver=1.10.5
ERRO[0000] error occurred while beginning pubsub pubsub: error getting topics from app: json: cannot unmarshal object into Go value of type []pubsub.SubscriptionJSON  app_id=spin-dapr-poc instance=kw-devvm scope=dapr.runtime type=log ver=1.10.5
```

root cause is that Dapr loads the pubsub component from `~/.dapr` folder 

```
INFO[0000] component loaded. name: pubsub, type: pubsub.redis/v1  app_id=spin-dapr-poc
```

which does not work in my clean/new installation. This is why I introduced the explicit `components` folder instead of relying on the `~/.dapr` folder

----

Then I misled myself believing that my variant was working because I did not clear state before my tests:

```
curl -H "dapr-app-id: spin-dapr-poc" -X DELETE http://localhost:3500/v1.0/state/statestore/257
```

According to [v1.10 docs](https://docs.dapr.io/reference/api/state_api/#example) state needs to be posted as an array which now incorporated into my last tested commit:

```
  // create a new order
  const orders = [{
    key: orderId.toString(),
    value: { orderId: orderId }
  }];

  const req = await fetch(`${stateStoreBaseUrl}?metadata.contentType=application/json`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify(orders)
    }
  );
```

----

So this version now works for me on my clean installation. If it also works for you I of course leave it up to you, whether you want to merge the PR.

Next thing I would want to fix is that during Dapr start up, when Dapr is checking application health, that not the whole logic of `handleRequest` is processed but that the **health checking** request is handled differently.

2023-04-24 16:19 UTC, danbugs requested changes
This is LGTM, and I'm good to merge it after this change – Thanks again for the PR. I really appreciate contributions!

2023-04-24 16:19 UTC, danbugs commented on src/index.ts
> +    body: ""
This has to be:
```suggestion
    body: encoder.encode("").buffer
```

Otherwise, `spin build` fails with:
```sh
➜  spin-dapr-poc git:(2023-04-rework) spin build
Executing the build command for component spin-dapr-poc: npm run build
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hello_world@1.0.0 build: `npx webpack --mode=production && mkdir -p target && spin js2wasm -o target/spin-http-js.wasm dist/spin.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hello_world@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/danbugs/.npm/_logs/2023-04-24T16_12_58_808Z-debug.log

> hello_world@1.0.0 build /Users/danbugs/repos/spin-dapr-poc
> npx webpack --mode=production && mkdir -p target && spin js2wasm -o target/spin-http-js.wasm dist/spin.js

assets by status 6.27 KiB [cached] 1 asset
runtime modules 670 bytes 3 modules
./src/index.ts 4.56 KiB [built] [code generated] [1 error]

ERROR in /Users/danbugs/repos/spin-dapr-poc/src/index.ts
./src/index.ts 47:4-8
[tsl] ERROR in /Users/danbugs/repos/spin-dapr-poc/src/index.ts(47,5)
      TS2322: Type 'string' is not assignable to type 'ArrayBuffer'.
ts-loader-default_e3b0c44298fc1c14
```

2023-04-24 16:23 UTC, radu-matei commented on src/index.ts
> +    body: ""
If you update the Spin plugin and SDK to the latest versions, this should work.

2023-04-24 17:10 UTC, KaiWalter commented on src/index.ts
> +    body: ""
right, I also upgraded spin-js-jdk to get it working

2023-04-24 17:49 UTC, danbugs commented on src/index.ts
> +    body: ""
Oops, my bad~ I prob. have an outdated version. I'm merging this now.

2023-04-24 17:49 UTC, danbugs approved these changes

2023-04-24 17:49 UTC, merged